apiVersion: v1
kind: Pod
metadata:
  generateName: gvisor-repro-
  labels:
    gvisor-repro: "true"
spec:
  runtimeClassName: gvisor
  restartPolicy: Never
  tolerations:
    - effect: NoSchedule
      key: mynerva.io/node-pool
      operator: Equal
      value: user-kernels
  containers:
  - name: test
    image: docker.io/travigd/gcp-gvisor-corruption-repro:latest
    imagePullPolicy: Always